# Generated by Django 4.0.4 on 2022-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
